name = "codenetic"
main = "./worker.js"  # Required even for static sites, just a dummy placeholder
compatibility_date = "2025-04-23"

[assets]
directory = "public"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false



